# Sets CMAKE_BASE_OS, CMAKE_BASE_ARCH, CMAKE_BASE_PLATFORM_SEGMENT (e.g. windows_x86-64, linux_aarch64).
# Exposes cmake_base_target_platform_definitions / cmake_base_target_architecture_definitions.

# --- OS ---

if(CMAKE_SYSTEM_NAME STREQUAL "Windows")
	set(CMAKE_BASE_OS "windows")
elseif(CMAKE_SYSTEM_NAME STREQUAL "Linux")
	set(CMAKE_BASE_OS "linux")
elseif(CMAKE_SYSTEM_NAME STREQUAL "Darwin")
	set(CMAKE_BASE_OS "darwin")
else()
	set(CMAKE_BASE_OS "unknown")
	message(WARNING "cmake-base: unrecognized CMAKE_SYSTEM_NAME='${CMAKE_SYSTEM_NAME}'; using CMAKE_BASE_OS=unknown")
endif()

# --- Arch (target processor) ---

string(TOLOWER "${CMAKE_SYSTEM_PROCESSOR}" _cmake_base_proc)

set(_cmake_base_arch "")
if(_cmake_base_proc STREQUAL "")
	set(_cmake_base_arch "unknown")
	message(WARNING "cmake-base: CMAKE_SYSTEM_PROCESSOR is empty; using CMAKE_BASE_ARCH=unknown")
elseif(_cmake_base_proc MATCHES "^(amd64|x86_64)$")
	set(_cmake_base_arch "x86-64")
elseif(_cmake_base_proc MATCHES "^(i386|i686|x86)$")
	set(_cmake_base_arch "x86-32")
elseif(_cmake_base_proc MATCHES "^(arm64|aarch64)$")
	set(_cmake_base_arch "aarch64")
elseif(_cmake_base_proc MATCHES "^riscv32")
	set(_cmake_base_arch "riscv32")
elseif(_cmake_base_proc MATCHES "^riscv64")
	set(_cmake_base_arch "riscv64")
elseif(
	(_cmake_base_proc MATCHES "^armv[0-9]")
	OR (_cmake_base_proc STREQUAL "arm")
	OR (_cmake_base_proc MATCHES "^armeb")
)
	set(_cmake_base_arch "aarch32")
else()
	set(_cmake_base_arch "unknown")
	message(WARNING "cmake-base: unrecognized CMAKE_SYSTEM_PROCESSOR='${CMAKE_SYSTEM_PROCESSOR}' (normalized='${_cmake_base_proc}'); using CMAKE_BASE_ARCH=unknown")
endif()

set(CMAKE_BASE_ARCH "${_cmake_base_arch}")
unset(_cmake_base_arch)
unset(_cmake_base_proc)

set(CMAKE_BASE_PLATFORM_SEGMENT "${CMAKE_BASE_OS}_${CMAKE_BASE_ARCH}")

# --- Target helpers ---

function(cmake_base_target_platform_definitions target prefix)
	if(NOT prefix MATCHES "^[A-Za-z_][A-Za-z0-9_]*$")
		message(FATAL_ERROR "cmake_base_target_platform_definitions: invalid prefix '${prefix}' (need C identifier stem)")
	endif()
	if(CMAKE_BASE_OS STREQUAL "windows")
		target_compile_definitions("${target}" PRIVATE "${prefix}_PLATFORM_WINDOWS=1")
	elseif(CMAKE_BASE_OS STREQUAL "linux")
		target_compile_definitions("${target}" PRIVATE "${prefix}_PLATFORM_LINUX=1")
	elseif(CMAKE_BASE_OS STREQUAL "darwin")
		target_compile_definitions("${target}" PRIVATE "${prefix}_PLATFORM_DARWIN=1")
	elseif(CMAKE_BASE_OS STREQUAL "unknown")
		target_compile_definitions("${target}" PRIVATE "${prefix}_PLATFORM_UNKNOWN=1")
	else()
		message(FATAL_ERROR "cmake_base_target_platform_definitions: internal error, CMAKE_BASE_OS='${CMAKE_BASE_OS}'")
	endif()
endfunction()

function(cmake_base_target_architecture_definitions target prefix)
	if(NOT prefix MATCHES "^[A-Za-z_][A-Za-z0-9_]*$")
		message(FATAL_ERROR "cmake_base_target_architecture_definitions: invalid prefix '${prefix}' (need C identifier stem)")
	endif()
	if(CMAKE_BASE_ARCH STREQUAL "x86-32")
		set(_suffix "X86_32")
	elseif(CMAKE_BASE_ARCH STREQUAL "x86-64")
		set(_suffix "X86_64")
	elseif(CMAKE_BASE_ARCH STREQUAL "aarch32")
		set(_suffix "AARCH32")
	elseif(CMAKE_BASE_ARCH STREQUAL "aarch64")
		set(_suffix "AARCH64")
	elseif(CMAKE_BASE_ARCH STREQUAL "riscv32")
		set(_suffix "RISCV32")
	elseif(CMAKE_BASE_ARCH STREQUAL "riscv64")
		set(_suffix "RISCV64")
	elseif(CMAKE_BASE_ARCH STREQUAL "unknown")
		set(_suffix "UNKNOWN")
	else()
		message(FATAL_ERROR "cmake_base_target_architecture_definitions: internal error, CMAKE_BASE_ARCH='${CMAKE_BASE_ARCH}'")
	endif()
	target_compile_definitions("${target}" PRIVATE "${prefix}_ARCHITECTURE_${_suffix}=1")
	unset(_suffix)
endfunction()
